name: Integration

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

jobs:
  integration:
    name: Mattermost ${{ matrix.mattermost-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 25
    strategy:
      fail-fast: false
      matrix:
        mattermost-version: 
          - '11.9.0' # latest
          - '11.7.8' # curret lts
          - '10.11.22' # previous lts
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - name: Run integration tests
        run: npm run test:integration
